[project]
name = "llm-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-google-genai>=3.2.0",
    "openai>=2.8.1",
    "streamlit>=1.51.0",
]
